server:
  port: 8087

spring:
  application:
    name: shop-user-consumer
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://175.178.16.179:3306/shop?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: hellomysql6B
  redis:
    host: 175.178.16.179
    password: 123456
  elasticsearch:
    rest:
      uris: http://192.168.204.99:9200 # ElasticSearch地址

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://175.178.16.179:8000/eureka # 注册中心地址

