server:
  port: 8083

spring:
  application:
    name: shop-search-provider
  profiles:
    active: provider-config

# hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 50000

  # ribbon的超时时间
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000