server:
  port: 9007

spring:
  application:
    name: shop-alipay-web
  thymeleaf:
    cache: false
  profiles:
    active: consumer-config

# 支付宝相关配置（使用支付宝公钥和应用私钥）
alipay:
  app_id: 90000134663801
  merchant_private_key: MIIEIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCYELSuVqMRbTyExgY07HFlPGisgZVtcMcsKV6g4zFB4eVJYEdlp3w1T+mkOf3+Gy+hpb/p9fed+tuU03xs8BR+AK1JFCl26SflN+Ktzqka9T9NZYj7bJiPj4RhwczOBSATQgHnOOHVY5hnbzrKktgbKelhqkTk2JChIwnDIDd8raus+p8XRy6FQ52LTrNPvJBc8Yt6BsuVRBc0FVCgDWQFCepnq7GLuA2dIQjVSKiUh/UEu4JQ+YsqVHEZSn9nCbEvoqwEc7i4KJ6wEj1mnEYpy9sCrNkGF8wXyMhKSSm59ANXsdrIN5Aft90GOgA9ddquScd2blrEE2kUQXjenHcXAgMBAAECggEAFBIQZvpUZ5ZtaHDinNWgWeZRQoOP/3PlNfT34nBaLgHsy3SDt+0VPcwgYGavGXzpGoLQA8dNOXLEzK3lPFOrwL3CIWUh2+oGNADeUGZ4d3BrPIHsRJMex8P/iw+TQpX2l9QcgDJHzGxqzywlLFuZXmx3u0ZH9ZSH8ly3iyOTb0cgxrs3Ds7BssWrIQGIz7cwzfk6mHo83AyGR2ToeqZ/OddSaUioIseITamGD/v8HPDZDF4/ls2kth9rw0nVQZzY0x6WjS+SuN61sbTPe8Et8aYc4Wm1R4yjcMiRw1dMSmtQpdlq/UhXcRYuILzRj3byXrklRK8TUhVbuIQjnnCY0QKBgQDMB+9CE+ZMrrwN2EK9UbGexRHrJ1BIh/nOrz7Y9gohriF476NibRIB6BiP9D856L13kZ8lZaS/bQQja2Fx11MkPfkSTQBdpSDuLhmRTT2/sQ5fdot6LFmkXuc8T2uqYX59Gi7KAZdeG09bL28ircPZtl4AZ1109qS8nyKoyOqbtQKBgQC+zEnBsiyaDbbMaL4hZsBJ7jta5qpHcDdVIQHMf13THCyuxccJ8UJWIj7CHNFvWpytPWLra2Iv9NSoR4W2+1GeDRXPlj2sJw2mq3L7/WlduVDK76v5ibglyTenNdjVD+cjmBJmlOzimaOpeDyfDCiRWC3z/VuYpILsNawJuCq/GwKBgFuhoKGDgGWmAA0Tt/2AiA3vIboDgPniH53kdIxKC4jOxHek4DLfGzxB+W4FWrPuQ9FEVD4eZRwXoMkre6r98ngPYSIH9QcZly2BBLiOARJrOTJEciWfb27ztFQQsyDlAkK7FJJinpGEIGKqbfYcJh5L2fHCemWCM8AGlDFLcpoVAoGBAL6TpVRxGPXjnuQ79zW7wXPXHrhkUE88+jfw2TAfRGNa8BK+gFog/oa0fAU97cARPRAZkdXek9uc7FEN57TnARYisdeAlSeAdrU06YxkCbvRH68kiJ2e/y3W99zv/x6KXPCDtFV8icSpe/0JmVuwNFFBR90/Ax/Lqu4viiDHMQNjAoGACCakrHTa8HOf3GD07HavfyDjobFL1+2q6vgynaId8ymA9THeMCBs73kRofrMuY2ka2v/m8pQ5rFXSI+eRmsqW7SvPQJpm5lMHs2YaPLu4aKDb970Ald1FDqtKwKBw/WoJFqMjdtvPjDr4Zs8aUWrlKkX+/N8HaI0VzO3T1H5rUk=
  alipay_public_key: MIIBANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0dDOYMKci+Hrffcy1MV8eT4PZCbo9ahRLai6amUtMC9QgwrPg0QUj1HNXRpJ876VWWdqLSDQLS5BSn3aTLLFmh2de63Wxym/MgmWD8jtuOcnG+mx2N+ES51oFysn1MSxeHgdVLmX9YyrDBfnI0XQbtOnuc9rzKk2Axz7aBT7PR1OUD/qboe3fWRVGkOq+0FQmlHPLkGcUMutv0IOfzLqrAS+15fJ7WTAN6bKs4+g1SG7mRAs/Xbjz8NVLI/uUMPpmmjmPSTBsMRgBMuc6Jn+qLoIz7zTy75EQrI4UdA3EeDGR66bt1K2zGWnjr94UhSJfxi9LIiwmgzRvjSbQcP4WQIDAQAB
  notify_url: http://vndgw7.natappfree.cc/shop/alipay/notify  # 异步通知地址
  return_url: http://localhost:8081/shop/order/index # 同步通知地址
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  log_path: D:\\CodeRepository\\alipay_java_utf8


