spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://175.178.16.179:3306/shop?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  elasticsearch:
    rest:
      uris: http://192.168.204.99:9200 # ElasticSearch地址

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://175.178.16.179:8000/eureka # 注册中心地址

# hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 50000

  # ribbon的超时时间
ribbon:
  ReadTimeout: 500000
  ConnectTimeout: 500000