server:
  port: 9002

spring:
  application:
    name: shop-product-detail-web
  thymeleaf:
    cache: false
  profiles:
    active: consumer-config
  redis:
    host: 175.178.16.179
    password: 123456